<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DvsaLogger\Module'                                                                           => __DIR__ . '/Module.php',
  'DvsaLogger\Factory\ApiClientLoggerFactory'                                                   => __DIR__ . '/src/DvsaLogger/Factory/ApiClientLoggerFactory.php',
  'DvsaLogger\Factory\ApiRequestExtrasFactory'                                                  => __DIR__ . '/src/DvsaLogger/Factory/ApiRequestExtrasFactory.php',
  'DvsaLogger\Factory\ApiRequestLoggerFactory'                                                  => __DIR__ . '/src/DvsaLogger/Factory/ApiRequestLoggerFactory.php',
  'DvsaLogger\Factory\ApiResponseExtrasFactory'                                                 => __DIR__ . '/src/DvsaLogger/Factory/ApiResponseExtrasFactory.php',
  'DvsaLogger\Factory\ApiResponseLoggerFactory'                                                 => __DIR__ . '/src/DvsaLogger/Factory/ApiResponseLoggerFactory.php',
  'DvsaLogger\Factory\DoctrineQueryExtrasFactory'                                               => __DIR__ . '/src/DvsaLogger/Factory/DoctrineQueryExtrasFactory.php',
  'DvsaLogger\Factory\DoctrineQueryLoggerFactory'                                               => __DIR__ . '/src/DvsaLogger/Factory/DoctrineQueryLoggerFactory.php',
  'DvsaLogger\Factory\DoctrineQueryLoggerServiceFactory'                                        => __DIR__ . '/src/DvsaLogger/Factory/DoctrineQueryLoggerServiceFactory.php',
  'DvsaLogger\Factory\ExtrasFactory'                                                            => __DIR__ . '/src/DvsaLogger/Factory/ExtrasFactory.php',
  'DvsaLogger\Factory\FrontendRequestLoggerFactory'                                             => __DIR__ . '/src/DvsaLogger/Factory/FrontendRequestLoggerFactory.php',
  'DvsaLogger\Listener\ApiClientRequest'                                                        => __DIR__ . '/src/DvsaLogger/Listener/ApiClientRequest.php',
  'DvsaLogger\Listener\ApiRequest'                                                              => __DIR__ . '/src/DvsaLogger/Listener/ApiRequest.php',
  'DvsaLogger\Listener\ApiResponse'                                                             => __DIR__ . '/src/DvsaLogger/Listener/ApiResponse.php',
  'DvsaLogger\Listener\FrontendRequest'                                                         => __DIR__ . '/src/DvsaLogger/Listener/FrontendRequest.php',
  'DvsaLogger\Processor\ApiRequestExtras'                                                       => __DIR__ . '/src/DvsaLogger/Processor/ApiRequestExtras.php',
  'DvsaLogger\Processor\ApiResponseExtras'                                                      => __DIR__ . '/src/DvsaLogger/Processor/ApiResponseExtras.php',
  'DvsaLogger\Processor\DoctrineQueryExtras'                                                    => __DIR__ . '/src/DvsaLogger/Processor/DoctrineQueryExtras.php',
  'DvsaLogger\Processor\Extras'                                                                 => __DIR__ . '/src/DvsaLogger/Processor/Extras.php',
  'DvsaLogger\Service\DoctrineQueryLoggerService'                                               => __DIR__ . '/src/DvsaLogger/Service/DoctrineQueryLoggerService.php',
);
