name: CI

on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 
      - 'main'
  schedule:
    - cron: '0 0 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  static:
    uses: dvsa/.github/.github/workflows/php-static.yml@v4.1.0
    with:
      php-version: "8.1"      
      composer-version: 'v2.2.24'

  test:
    uses: dvsa/.github/.github/workflows/php-tests.yml@v4.1.0
    with:
      php-versions: "[\"8.1\"]"      
      composer-version: 'v2.2.24'

  security:
    uses: dvsa/.github/.github/workflows/php-security.yml@v4.1.0    
    with:
      php-version: '8.1'
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
