name: CI

on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 
      - 'main'
  schedule:
    - cron: '0 0 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  static:
    uses: dvsa/.github/.github/workflows/php-library-static.yml@v4.0.1
    with:
      php-version: "8.1"

  test:
    uses: dvsa/.github/.github/workflows/php-library-tests.yml@v3.2.3
    with:
      php-versions: "[\"8.1\"]"

  security:
    uses: dvsa/.github/.github/workflows/php-library-security.yml@v3.2.3
    with:
     php-versions: "[\"8.1\"]"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
