name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  test:
    uses: dvsa/.github/.github/workflows/php-tests.yml@v3.2.2
    with:
     php-versions: "[\"8.0\", \"8.1\"]"
